config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products, :comments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	root to: 'products#index'

	resources :products do
		member do 
			post 'upvote'
		end
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

	belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord

#----Validations

validates :title, :description, :link, presence: true
has_many :comments 
has_many :votes



end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :votes       
end

app/models/vote.rb
class Vote < ApplicationRecord

	belongs_to :user
	belongs_to :product

	validates_presence_of :product_id, :user_id
	validates_uniqueness_of :user_id, scope: :product_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:comment, :user_id)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	def index
		@products = Product.all

	end

	def test
	
	end
	#DELETE /products/1

#POSTS /posts/:id/upvote
	def upvote
		@product = Product.find(parms[:id])
		@vote = @product.votes.new(user_id: current_user)
		if @vote.save
			redirect_to products_path, notice: 'Post was succesfully upvoted'
		else
			redirect_to products_path, notice: 'You have already voted'
		end
	end		
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for(comment) do |f| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comment %>
    <%= f.text_field :comment %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Comment</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.comment %></td>
        <td><%= comment.user_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comment:</strong>
  <%= @comment.comment %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProductHunt</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
  <header class="main-header">
			<div class="header-wrap">
		      <a href="https://www.producthunt.com" class="logo-link">
		        <img src ="img/logo.png" alt="Product Hunt Logo" class ="logo">
		      </a>

					<!-- <img src="img/search-icon.png" height="15px" class="search-icon"> -->
					<!-- <i class="fa fa-search" aria-hidden="true"></i> -->
					<form class="search-form">
				    <input type="text" class="search-bar" placeholder="Discover your next favourite thing...">
				  </form>


		      <a href="#" class="dropdown-tabs">...</a>
		      <a href="#" class="login-button">login</a>
		      <nav class="main-nav">
		        <a class="main-nav__link-active" href="#">
							<p class="main-nav__link-text">Home</p>
						</a>
		        <a class="main-nav__link nav__link-1" href="#">
							<p class="main-nav__link-text">Tech</p>
						</a>
		        <a class="main-nav__link nav__link-2" href="#">
							<p class="main-nav__link-text">Games</p>
						</a>
		        <a class="main-nav__link nav__link-3" href="#">
							<p class="main-nav__link-text">Podcasts</p>
						</a>
		        <a class="main-nav__link nav__link-4" href="#">
							<p class="main-nav__link-text">Books</p>
						</a>
		        <a class="main-nav__link nav__link-5" href="#">
							<p class="main-nav__link-text">Bots</p>
						</a>
		        <a class="main-nav__link nav__link-6" href="#">
							<p class="main-nav__link-text">Developer Tools</p>
							</a>
		        <a class="main-nav__link nav__link-7" href="#">
							<p class="main-nav__link-text">Photography Tools</p>
						</a>
		        <a class="main-nav__link nav__link-8" href="#">
							<p class="main-nav__link-text">Pokemon</p>
						</a>
						<a class="main-nav__link nav__link-9" href="#">
							<p class="main-nav__link-text">Slack</p>
						</a>
						<a class="main-nav__link nav__link-10" href="#">
							<p class="main-nav__link-text">Wearables</p>
						</a>
		        <!-- <a class="main-nav__link-arrows" href="#">
							<p> < </p>
						</a>
		        <a class="main-nav__link-arrows" href="#">
							<p> > </p> -->
						</a>
		      </nav>
			</div>
	  </header>
    <%= yield %>
  </body>
</html>

app/views/products/_product.html.erb
<% @products.each do |product| %>
      <a href="#" class="product-link">
  			<img src="http://www.fillmurray.com/80/80" alt="Placeholder Bill Murray" class="product-image">
        <div class="product-content__text">
					<h2 class="product-titles">Bill Murray</h2>
        	<p class="product-description">Bill Murray Bill Murray Bill Murray Bill Murray Bill Murray</p>
					<div class="product-buttons">
						<div class="upvote-button"> </div>
						<div class="comment-button">7</div>
						<div class="save-button">save</div>
						<div class="share-button"></div>
						<div class="product-tag">pokemon</div>
					</div>
				</div>
  		</a>
  		<%end%>

app/views/products/index.html.erb
<div class="content-wrap">
	<div class="link-wrap">
		<div class="h5-wrap"><h5 class="section-title">While you were away</h5></div>
	  <section class="product-links">
<% @products.each do |product| %>
<%= button_to upvote_product_path(product), class: 'upvote' do %>
&#9650;
<br>
<span class = "votes"><%= product.votes.count%></span<span>
<%end%>

      <a href="#" class="product-link">
  			<img src="http://www.fillmurray.com/80/80" alt="Placeholder Bill Murray" class="product-image">
        <div class="product-content__text">
					<h2 class="product-titles">Bill Murray</h2>
        	<p class="product-description">Bill Murray Bill Murray Bill Murray Bill Murray Bill Murray</p>
					<div class="product-buttons">
						<div class="upvote-button"> </div>
						<div class="comment-button">7</div>
						<div class="save-button">save</div>
						<div class="share-button"></div>
						<div class="product-tag">pokemon</div>
					</div>
				</div>
  		</a>
  		<%end%>
<!-- 
      <a href="#" class="product-link">
        <img src="http://www.fillmurray.com/80/80" alt="Placeholder Bill Murray" class="product-image">
				<div class="product-content__text">
					<h2 class="product-titles">Bill Murray</h2>
					<p class="product-description">Bill Murray</p>
					<div class="product-buttons">
						<div class="upvote-button"> </div>
						<div class="comment-button">7</div>
						<div class="save-button">save</div>
						<div class="share-button"></div>
						<div class="product-tag">productivity</div>
					</div>
				</div>
      </a>

      <a href="#" class="product-link">
        <img src="http://www.fillmurray.com/80/80" alt="Placeholder Bill Murray" class="product-image">
				<div class="product-content__text">
					<h2 class="product-titles">Bill Murray Bill Murray Bill Murray Bill Murray Bill Murray Bill Murray Bill Murray Bill Murray Bill Murray Bill Murray Bill Murray Bill Murray</h2>
					<p class="product-description">Bill Murray</p>
					<div class="product-buttons">
						<div class="upvote-button"> </div>
						<div class="comment-button">7</div>
						<div class="save-button">save</div>
						<div class="share-button"></div>
						<div class="product-tag">developer tools</div>
					</div>
				</div>
      </a>

			<a href="#" class="product-link">
				<img src="http://www.fillmurray.com/80/80" alt="Placeholder Bill Murray" class="product-image">
				<div class="product-content__text">
					<h2 class="product-titles">Bill Murray</h2>
					<p class="product-description">Bill Murray Bill Murray Bill Murray Bill Murray Bill Murray</p>
					<div class="product-buttons">
						<div class="upvote-button"> </div>
						<div class="comment-button">7</div>
						<div class="save-button">save</div>
						<div class="share-button"></div>
						<div class="product-tag">pokemon</div>
					</div>
				</div>
			</a>

			<a href="#" class="product-link">
				<img src="http://www.fillmurray.com/80/80" alt="Placeholder Bill Murray" class="product-image">
				<div class="product-content__text">
					<h2 class="product-titles">Bill Murray</h2>
					<p class="product-description">Bill Murray Bill Murray Bill Murray Bill Murray Bill Murray</p>
					<div class="product-buttons">
						<div class="upvote-button"> </div>
						<div class="comment-button">7</div>
						<div class="save-button">save</div>
						<div class="share-button"></div>
						<div class="product-tag">pokemon</div>
					</div>
				</div>
			</a>

			<a href="#" class="product-link">
				<img src="http://www.fillmurray.com/80/80" alt="Placeholder Bill Murray" class="product-image">
				<div class="product-content__text">
					<h2 class="product-titles">Bill Murray</h2>
					<p class="product-description">Bill Murray Bill Murray Bill Murray Bill Murray Bill Murray</p>
					<div class="product-buttons">
						<div class="upvote-button"> </div>
						<div class="comment-button">7</div>
						<div class="save-button">save</div>
						<div class="share-button"></div>
						<div class="product-tag">pokemon</div>
					</div>
				</div>
			</a>
 -->
		</section>
  </div>

	<div class="sidebar hidden">

		<section class="sidebar-recommendation">
				<h2 class="sidebar-recommendation__title">Kittybot for Slack.</h2>
				<p class="sidebar-recommendation__description">A friendly feline that sends you cool new things.</p>
				<a href="#" class="sidebar-recommendation__button">
					<i class="fa fa-slack" aria-hidden="true"></i>
					<p class="sidebar-button__text">add kittybot to slack</p>
				</a>
		</section>

		<section class="sidebar-chats">
			<h5 class="upcoming-chats">upcoming live chats</h5>
				<div class="sidebar-chats__vips">
						<a href="#" class="vip-picture__link">
					 		<img src="http://www.placekitten.com/35/35" alt="Placeholder Kitten" class="vip-picture__image">
						</a>
						<div class="vip-info">
							<a href="#" class="vip-name__link"><h5 class="vip-name">This Kitten</h5></a>
							<p class="vip-description">A real cool cat</p>
							<a href="#" class="reminder-button">remind me</a>
						</div>
				</div>

				<div class="sidebar-chats__vips">
						<a href="#" class="vip-picture__link">
					 		<img src="http://www.placecage.com/35/35" alt="Placeholder Cage" class="vip-picture__image">
						</a>
						<div class="vip-info">
							<a href="#" class="vip-name__link"><h5 class="vip-name">Nicholas Cage</h5></a>
							<p class="vip-description">Put... the bunny... back in the box</p>
							<a href="#" class="reminder-button">remind me</a>
						</div>
				</div>

				<div class="sidebar-chats__vips">
						<a href="#" class="vip-picture__link">
							<img src="http://www.placebear.com/35/35" alt="Placeholder Bear" class="vip-picture__image">
						</a>
						<div class="vip-info">
							<a href="#" class="vip-name__link"><h5 class="vip-name">It's a Bear</h5></a>
							<p class="vip-description">He does bear things</p>
							<a href="#" class="reminder-button">remind me</a>
						</div>
				</div>

				<div class="sidebar-chats__vips">
						<a href="#" class="vip-picture__link">
							<img src="http://www.stevensegallery.com/35/35" alt="Placeholder Steven Segall" class="vip-picture__image">
						</a>
						<div class="vip-info">
							<a href="#" class="vip-name__link"><h5 class="vip-name">Steven Segall</h5></a>
							<p class="vip-description">He stopped some terrorists somewhere</p>
							<a href="#" class="reminder-button">remind me</a>
						</div>
				</div>

				<div class="sidebar-chats__vips">
						<a href="#" class="vip-picture__link">
							<img src="http://www.fillmurray.com/35/35" alt="Placeholder Murray" class="vip-picture__image">
						</a>
						<div class="vip-info">
							<a href="#" class="vip-name__link"><h5 class="vip-name">Bill Murray</h5></a>
							<p class="vip-description">Who you gonna call?</p>
							<a href="#" class="reminder-button">remind me</a>
						</div>
				</div>

				<a href="#" class="more-chats__link"><p class="more-chats">see more</p></a>
		</section>
	</div>
</div>

</div>